name: speedy
description: "Offline GPS speedometer with trip history"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # GPS
  geolocator: ^14.0.2

  # UI
  google_fonts: ^6.1.0

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_mobile_ads: ^7.0.0
  intl: ^0.19.0
  provider: ^6.1.2
  fl_chart: ^0.67.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0  
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  analyzer: ^6.4.1

  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_foreground: assets/icon/icon.png
  adaptive_icon_background: "#ffffff"

  


flutter:
  uses-material-design: true
